### ISSUE TITLE
Non-Chrome Google Lens errors?

### ISSUE THREAD

**Issue by kittyifcat** [AuroraWright/owocr#6] opened 2024-12-17 19:51 UTC
I've been trying to use google lens through owocr today, but all i get are "Connection error!" and, when I don't, "Regex error".
Thinking that maybe google lens itself was down, I tried using lens.google.com with firefox, and the image turned into nothing but lines.
But when I tried with chrome, both the google lens search built into the browser, and lens.google.com worked.

![Screenshot from 2024-12-17 20-29-39](https://github.com/user-attachments/assets/51f281a6-de07-4fac-9017-d85c00a7322f)
![Screenshot from 2024-12-17 20-30-10](https://github.com/user-attachments/assets/07e55e35-0ee2-49c3-b28a-3294e9330336)

**Comment by phamthaison1207** [comment] 2024-12-17 22:22
second this, google lens api is changed due to google's new redesign

**Comment by AuroraWright** [comment] 2024-12-17 23:49
It seems they still use the old version depending on the user agent. The new version requires more effort from the look of it (and might be slower due to more calls involved). For now I'm trying to force the old version, try updating with pip install --upgrade owocr

**Comment by kittyifcat** [comment] 2024-12-18 00:22
> It seems they still use the old version depending on the user agent. The new version requires more effort from the look of it (and might be slower due to more calls involved). For now I'm trying to force the old version, try updating with `pip install --upgrade owocr`

upgraded to 1.8.4 and rebooted the router before testing, but the issue persists

**Comment by AuroraWright** [comment] 2024-12-18 03:15
> > It seems they still use the old version depending on the user agent. The new version requires more effort from the look of it (and might be slower due to more calls involved). For now I'm trying to force the old version, try updating with `pip install --upgrade owocr`
> 
> upgraded to 1.8.4 (took a few tries, the command installed 1.7.6 for some reason initially) and rebooted the router before testing, but the issue persists

I'm not sure how to reproduce it since it all works reliably on my end now. I tried a few different locations with my VPN and it also still works all the time. Maybe it's weird Google A/B testing. I guess let's hear from the others

**Comment by kittyifcat** [comment] 2024-12-18 09:03
> > > It seems they still use the old version depending on the user agent. The new version requires more effort from the look of it (and might be slower due to more calls involved). For now I'm trying to force the old version, try updating with `pip install --upgrade owocr`
> > 
> > 
> > upgraded to 1.8.4 (took a few tries, the command installed 1.7.6 for some reason initially) and rebooted the router before testing, but the issue persists
> 
> I'm not sure how to reproduce it since it all works reliably on my end now. I tried a few different locations with my VPN and it also still works all the time. Maybe it's weird Google A/B testing. I guess let's hear from the others
> 
> I'd also try uninstalling and reinstalling owocr in case pip is somehow not updating it correctly

seems like while it happens on my steam deck, i can't reproduce it on my tablet (fedora 40)
before the update it happened on both

**Comment by AuroraWright** [comment] 2024-12-23 08:28
I haven’t had a single lens failure since the update and it has been reported working by multiple people at this point so i’m closing this for now (will reopen if google decides to break it again sigh)

**Closed by AuroraWright** 2024-12-23 08:28 UTC
